services:
  api-tests:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - LOCAL_URL=http://api:8000
      - POSTGRES_HOST=db
    command: [ "/bin/bash", "-c", "poetry run pytest menu_app_tests/*"]
