services:
  db:
    image: postgres:15.1-alpine
    env_file:
      - docker-compose.env

  redis:
    image: redis:7-alpine

  api:
    depends_on:
      db:
        condition: service_started
      redis:
        condition: service_started
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - docker-compose.env
    ports:
      - 8000:8000
