name: pre-commit-check

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  pre-commit-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Init venv
        run: |
          python -m venv .venv
          source .venv/bin/activate
          echo "PATH=$PATH" >> $GITHUB_ENV

      - name: Install depenpencies
        run: |
          pip install poetry
          poetry install

      - name: Run pre-commit task
        run: poetry run pre-commit run --all-files
